/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_myrtle_atomic_jni_macos_PhotosKit */

#ifndef _Included_org_myrtle_atomic_jni_macos_PhotosKit
#define _Included_org_myrtle_atomic_jni_macos_PhotosKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_myrtle_atomic_jni_macos_PhotosKit
 * Method:    addImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_myrtle_atomic_jni_macos_PhotosKit_addImage
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
